config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :restaurants do
      resources :reviews
    end
  end

  resources :restaurants, only: [:new, :create, :show, :index] do
    resources :reviews, only: [:new, :create, :show]
  end
  root to: 'restaurants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = %w[chinese italian japanese french belgian].freeze
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, inclusion: {
    in: CATEGORIES, message: CATEGORIES.join(' ').to_s
  }, presence: true
  # validates :img_url, format: {
  #   with: /.(gif|jpg|png)/i, message: 'must be a URL for GIF, JPG or PNG image.'
  # }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, inclusion: {
    in: [0, 1, 2, 3, 4, 5], message: 'must be from 0 to 5.'
  }
  validates :rating, numericality: true
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  before_action :set_restaurant
  before_action :set_restaurants
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @restaurant.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  private

  def set_restaurants
    @restaurants = Restaurant.all
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number, :img_url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    # @restaurants = Restarant.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/restaurants/_form.html.erb
<%= simple_form_for([:admin, @restaurant]) do |f| %>
<!--   <% if @restaurant.errors.any? %>
  <h3>OOps!!!! You have these errors:</h3>
  <ul>
    <% @restaurant.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
 -->
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category, collection: ['chinese', 'italian', 'japanese', 'french', 'belgian'], prompt: "Select your age", selected: 21 %>
    <%= f.input :phone_number %>
    <%= f.input :img_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/restaurants/edit.html.erb
<h2 class="page header">Edit restaurant page of: <%= @restaurant.name %></h2>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/admin/restaurants/show.html.erb
<div class="page header">
  <h2><%= @restaurant.name %></h2>
  <%=
    link_to "Delete",
    admin_restaurant_path(@restaurant),
    method: :delete,
    data: { confirm: "Are you sure?" }
  %>
  <%=
    link_to "Update",
    edit_admin_restaurant_path(@restaurant)
  %>
</div>
<div style="background-image: url(<%= @restaurant.img_url %>)" class="restaurant-img-full"></div>
<div class="page">
  <h4>Address:</h4>
  <p><%= @restaurant.address %></p>
  <br>
<!--   <h4>List of reviews:</h4>
  <%= link_to "Add Review", new_restaurant_review_path(@restaurant), class: 'btn-add-review'%>
  <ul class="reviews-list">
    <% @restaurant.reviews.each do |review| %>
      <li>
        <div class="review">
          <div class="review-content">
            <%= review.content %>
          </div>
          <div class="review-rating">
            <p>Rating: <%= review.rating %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul> -->
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <!-- <%= link_to "Home", "#", class: "navbar-wagon-item navbar-wagon-link" %> -->
    <!-- <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %> -->
    <!-- <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %> -->

    <!-- Avatar with dropdown menu -->
<!--     <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div> -->
  </div>

  <!-- Dropdown list appearing on mobile only -->
<!--   <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div> -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
<!--   <% if @restaurant.errors.any? %>
  <h3>OOps!!!! You have these errors:</h3>
  <ul>
    <% @restaurant.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
 -->
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category, collection: ['chinese', 'italian', 'japanese', 'french', 'belgian'], prompt: "Select your age", selected: 21 %>
    <%= f.input :phone_number %>
    <%= f.input :img_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/index.html.erb
<div class="page header">
  <h2 id="header-title">List of restaurants</h2>
  <p><%= link_to "Add new Restaurant", new_restaurant_path%></p>
</div>
<div id="restaurants-index">
  <% @restaurants.each do |restaurant| %>
  <div class="card col-sm-12 col-md-6 col-lg-4">
    <div class="restaurant">
      <%= link_to "", restaurant_path(restaurant), class: "fill-div" %>
      <div style="background-image: url(<%= restaurant.img_url %>)" class="restaurant-img"></div>
      <div class="restaurant-name"><%= restaurant.name %></div>
      <div class="restaurant-stars">3</div>
    </div>
  </div>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<h2 class="page header">New Restaurant</h2>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<div class="page header">
  <h2><%= @restaurant.name %></h2>
</div>
<div style="background-image: url(<%= @restaurant.img_url %>)" class="restaurant-img-full"></div>
<div class="page">
  <h4>Address:</h4>
  <p><%= @restaurant.address %></p>
  <br>
  <h4>List of reviews:</h4>
  <%= link_to "Add Review", new_restaurant_review_path(@restaurant), class: 'btn-add-review'%>
  <ul class="reviews-list">
    <% @restaurant.reviews.each do |review| %>
      <li>
        <div class="review">
          <div class="review-content">
            <%= review.content %>
          </div>
          <div class="review-rating">
            <p>Rating: <%= review.rating %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/reviews/new.html.erb
<h2 class="page header">New review for <%= @restaurant.name %></h2>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>